
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: say_my_name

development:
  <<: *default
  database: studio_dev

development:
  <<: *default
  database: studio_test

production:
  <<: *default
  database: studio_prod
